### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ArthurNagy** [mmtrt/leagueoflegends#159]
Hey @mmtrt , thanks for this `snap` really great work! 
Unfortunately I'm unable to login, I'm getting the following error: 
```
000050.982| ALWAYS|           rcp-be-lol-login| Updating Login Credentials: UserPass
000050.990| ALWAYS|           rcp-be-lol-login| Beginning login.
000051.002| ALWAYS|           rcp-be-lol-login| PlatformId tracking: rso_platform_id: EUN1 (passed to RSOLogin/RSOStatus)
000051.011| ALWAYS|           rcp-be-lol-login| PlatformId tracking: region: EUNE (not used)
000051.019| ALWAYS|           rcp-be-lol-login| GapsLoginFlowEnabled: false
000051.025| ALWAYS|           rcp-be-lol-login| Creating login session object.
000051.037| ALWAYS|           rcp-be-lol-login| RSO: processing login session
000051.046| ALWAYS|           rcp-be-lol-login| RSOLogin: starting: EUN1
000051.054|   OKAY|           rcp-be-lol-store| HandleLogin calling CheckReady
000051.066|   OKAY| rcp-be-lol-platform-config| PlatformConfigPlugin::HandleLoginSession()
000051.082|   OKAY|        rcp-be-lol-gameflow| Did not relaunch game because user was not logged in.
000051.089| ALWAYS|           rcp-be-lol-store| StorePlugin init-status: in-progress ( LoggedIn StoreEndpoint Region Headers )
000051.096|   WARN|           rcp-be-lol-lobby| Can't check registration status, not connected
000051.099| ALWAYS|      rcp-be-lol-statstones| StatStonesPlugin init-status: in-progress ( StatStonesEnabled )
000051.102| ALWAYS|           rcp-be-lol-login| RSOLogin: creating new session
000051.195|   WARN|        rcp-be-lol-rso-auth| RSO received malformed body: Error converting response for POST https://auth.riotgames.com/token: body was empty
000051.199| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rso_token_request
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: AmLeZQ==
common.login_session_id: 1505c431-4b40-774a-bc4f-1e41060c5f83
common.locale: en_GB
common.os_version_major: 10
common.machine_id: SV1n57INYEmLvJ1ekkJKCg==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: 
common.region: EUNE
common.session_id: 921bd5c7-ad4a-2842-94b0-86dc2a76d1c4
error: malformed_body
error_description: Error converting response for POST https://auth.riotgames.com/token: body was empty
grant_type: password
succeeded: false
000051.217| ALWAYS| Queued Dradis event to be sent.
000051.218|  ERROR|           rcp-be-lol-login| RSOLogin: auth failed: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000051.221|   WARN|           rcp-be-lol-login| RSOLogin: failed: FAILED_TO_COMMUNICATE_WITH_RSO: RSO Server error: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000051.226| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__login_result
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: AmLeZQ==
common.login_session_id: 1505c431-4b40-774a-bc4f-1e41060c5f83
login_auth_duration_seconds: 0.200666
common.locale: en_GB
common.os_version_major: 10
common.machine_id: SV1n57INYEmLvJ1ekkJKCg==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: 
common.region: EUNE
common.session_id: 921bd5c7-ad4a-2842-94b0-86dc2a76d1c4
login_error.id: ALE-54000002
login_error.messageId: FAILED_TO_COMMUNICATE_WITH_RSO
login_overall_duration_seconds: 0.200679
login_succeeded: false
000051.241| ALWAYS| Queued Dradis event to be sent.
000051.248|   WARN|           rcp-be-lol-login| ProcessRSOLoginSession failed: FAILED_TO_COMMUNICATE_WITH_RSO: RSO Server error: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000051.253|   OKAY|           rcp-be-lol-store| HandleLogin calling CheckReady
000051.257|   OKAY| rcp-be-lol-platform-config| PlatformConfigPlugin::HandleLoginSession()
000051.260|   OKAY|        rcp-be-lol-gameflow| Did not relaunch game because user was not logged in.
000051.263| ALWAYS|           rcp-be-lol-store| StorePlugin init-status: in-progress ( LoggedIn StoreEndpoint Region Headers )
000051.266|   WARN|           rcp-be-lol-lobby| Can't check registration status, not connected
000051.269| ALWAYS|      rcp-be-lol-statstones| StatStonesPlugin init-status: in-progress ( StatStonesEnabled )
000051.272| ALWAYS|        rcp-be-lol-rso-auth| RSOAuthPlugin::HandleAuthorizationDelete()
000051.274|   WARN|           rcp-be-lol-login| RSO Login session procesing failed: FAILED_TO_COMMUNICATE_WITH_RSO
000051.277| ALWAYS|                    Tracing| The following message is being collected by the Data API - Channel: riot__rclient__lcu-player-experience-duration  Data: {"common.application_name":"LeagueClient","common.application_version":"10.22.341.643","common.cef_version":"74.1.19+gb62bacf+chromium-74.0.3729.157","common.client_id":"lol","common.installation_id":"AmLeZQ==","common.locale":"en_GB","common.login_session_id":"1505c431-4b40-774a-bc4f-1e41060c5f83","common.machine_id":"SV1n57INYEmLvJ1ekkJKCg==","common.os_edition":"Ultimate N, x64","common.os_platform":"Windows","common.os_version_major":"10","common.os_version_minor":"","common.region":"EUNE","common.session_id":"921bd5c7-ad4a-2842-94b0-86dc2a76d1c4","duration":"168296","occurrenceId":"0","tag":"lol-login-request-rso-token_fail_auth"}
000051.392|  ERROR|                   Remoting| HTTP Response 400 to GET '/lol-summoner/v1/summoners/null'
000051.394| ALWAYS|                    Tracing| The following message is being collected by the Data API - Channel: riot__rclient__lcu-player-experience-duration  Data: {"common.application_name":"LeagueClient","common.application_version":"10.22.341.643","common.cef_version":"74.1.19+gb62bacf+chromium-74.0.3729.157","common.client_id":"lol","common.installation_id":"AmLeZQ==","common.locale":"en_GB","common.login_session_id":"1505c431-4b40-774a-bc4f-1e41060c5f83","common.machine_id":"SV1n57INYEmLvJ1ekkJKCg==","common.os_edition":"Ultimate N, x64","common.os_platform":"Windows","common.os_version_major":"10","common.os_version_minor":"","common.region":"EUNE","common.session_id":"921bd5c7-ad4a-2842-94b0-86dc2a76d1c4","duration":"411998","occurrenceId":"0","tag":"login-successful-lock-and-load-unlock_failed"}
000051.414| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__feature_error
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: AmLeZQ==
common.login_session_id: 1505c431-4b40-774a-bc4f-1e41060c5f83
common.locale: en_GB
common.os_version_major: 10
common.machine_id: SV1n57INYEmLvJ1ekkJKCg==
localizationString: Unable to connect to the authentication service. Check the server status <a class='login-external-link' target='_blank' href='http://status.leagueoflegends.com/'>here</a>. If it looks good, follow the guide <a class='login-external-link' target='_blank' href='https://support.riotgames.com/hc/articles/201761944'>here</a>
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: 
plugin: rcp-fe-lol-login
common.region: EUNE
common.session_id: 921bd5c7-ad4a-2842-94b0-86dc2a76d1c4
id: LOGIN_BACKEND_ERROR_MESSAGE
messageId: FAILED_TO_COMMUNICATE_WITH_RSO
message: we recieved an error from /lol-login/v1/session/error
severity: unknown
sessionTime: 34761
000051.439| ALWAYS| Queued Dradis event to be sent.
000060.787|   OKAY|           rcp-be-lol-patch| Patchsieve response: {"releases":[{"release":{"product":"lol","id":"627273B2B005FA95","labels":{"branch":{"values":["releases-10-22"]},"buildtracker_config":{"values":["public-win32-packed-now-public"]},"code":{"values":["public"]},"content":{"values":["release"]},"cpuarch":{"values":["x86"]},"platform":{"values":["windows"]},"riot:artifact_type_id":{"values":["lol-game-client"]},"riot:artifact_version_id":{"values":["10.22.3410643+branch.releases-10-22.code.public.content.release.cpuarch.x86.platform.windows"]},"riot:cpu_arch":{"values":["x86"]},"riot:platform":{"values":["windows"]},"riot:revision":{"values":["3410643"]}}},"compat_version":{"id":"10.22.3410643+branch.releases-10-22.code.public.content.release"},"download":{"url":"https://lol.secure.dyn.riotcdn.net/channels/public/releases/627273B2B005FA95.manifest","scd_required":false}}]}
000060.875|   OKAY| Patcher: Resolving hostname lol.secure.dyn.riotcdn.net
000060.903|   OKAY| Patcher: Resolved hostname lol.secure.dyn.riotcdn.net in 0.021 secs: 86.124.128.227, 86.124.128.195
000060.915|   OKAY| Patcher: Started file download for URL https://lol.secure.dyn.riotcdn.net/channels/public/live-eune-win.json with ID 3 over connection 0 to server 8.241.99.117
000060.965|   OKAY| Patcher: Completed 388-byte 0-range file download request with ID 3 / unknown to server 8.241.99.117 from CDN unknown via POP unknown over connection 0 for URL https://lol.secure.dyn.riotcdn.net/channels/public/live-eune-win.json after 0.090 secs, 388 downloaded bytes and 0 retries
```

I've tried all the tricks I've found in the Github issues: refreshing WINEPREFIX, updating all dependencies.
I've also disabled IPv6 on my network and setup DNS to 8.8.8.8 and 8.8.4.4, but nothing helped.

Do you have any idea what could be the issue?

**Comment by mmtrt** [comment]
use script before login account it is known issue see https://github.com/mmtrt/leagueoflegends/issues/148#issuecomment-699645169

**Comment by ljpinho** [comment]
Hi @mmtrt , thanks for all your work!

I can't also login with my account, I have done everything I read in issues, including running the script and I allways got the message "Unable to connect to the authentication service. Check the server status here. If it looks good, follow the guide."

the script returns:
user@lp-hp:~$ ./launchleague.sh 
LeagueClientUx pid: 35965
Waiting for port 38297
user@lp-hp:~$ 

When I press "SIGN IN" I get following messages:

000280.601| ALWAYS|           rcp-be-lol-login| Updating Login Credentials: UserPass
000280.608| ALWAYS|           rcp-be-lol-login| Beginning login.
000280.626| ALWAYS|           rcp-be-lol-login| PlatformId tracking: rso_platform_id: EUW1 (passed to RSOLogin/RSOStatus)
000280.634| ALWAYS|           rcp-be-lol-login| PlatformId tracking: region: EUW (not used)
000280.642| ALWAYS|           rcp-be-lol-login| GapsLoginFlowEnabled: false
000280.648| ALWAYS|           rcp-be-lol-login| Creating login session object.
000280.657| ALWAYS|           rcp-be-lol-login| RSO: processing login session
000280.664| ALWAYS|           rcp-be-lol-login| RSOLogin: starting: EUW1
000280.672|   OKAY|           rcp-be-lol-store| HandleLogin calling CheckReady
000280.696|   OKAY| rcp-be-lol-platform-config| PlatformConfigPlugin::HandleLoginSession()
000280.711|   OKAY|        rcp-be-lol-gameflow| Did not relaunch game because user was not logged in.
000280.725| ALWAYS|           rcp-be-lol-store| StorePlugin init-status: in-progress ( LoggedIn StoreEndpoint Region Headers )
000280.740|   WARN|           rcp-be-lol-lobby| Can't check registration status, not connected
000280.748|  ERROR|                    Tracing| Didn't send telemetry for lol-login-flow-entire-login because end was missing
000280.761| ALWAYS|      rcp-be-lol-statstones| StatStonesPlugin init-status: in-progress ( StatStonesEnabled )
000280.770| ALWAYS|           rcp-be-lol-login| RSOLogin: creating new session
000280.977|   WARN|        rcp-be-lol-rso-auth| RSO received malformed body: Error converting response for POST https://auth.riotgames.com/token: body was empty
000280.990| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rso_token_request
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: 0pSXzA==
common.login_session_id: d2c35be4-9199-aa41-906d-fce9622320cb
common.locale: en_GB
common.os_version_major: 7
common.machine_id: blgald1BEkW/RsP6dWyFOQ==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: e5a44758-eb46-df44-bf50-6b117d285d9a
error: malformed_body
error_description: Error converting response for POST https://auth.riotgames.com/token: body was empty
grant_type: password
succeeded: false
000281.054| ALWAYS| Queued Dradis event to be sent.
000281.057|  ERROR|           rcp-be-lol-login| RSOLogin: auth failed: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000281.075|   WARN|           rcp-be-lol-login| RSOLogin: failed: FAILED_TO_COMMUNICATE_WITH_RSO: RSO Server error: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000281.095| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__login_result
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: 0pSXzA==
common.login_session_id: d2c35be4-9199-aa41-906d-fce9622320cb
login_auth_duration_seconds: 0.445812
common.locale: en_GB
common.os_version_major: 7
common.machine_id: blgald1BEkW/RsP6dWyFOQ==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: e5a44758-eb46-df44-bf50-6b117d285d9a
login_error.id: ALE-54000002
login_error.messageId: FAILED_TO_COMMUNICATE_WITH_RSO
login_overall_duration_seconds: 0.445848
login_succeeded: false
000281.156| ALWAYS| Queued Dradis event to be sent.
000281.163| ALWAYS|                    Tracing| The following message is being collected by the Data API - Channel: riot__rclient__lcu-player-experience-duration  Data: {"common.application_name":"LeagueClient","common.application_version":"10.22.341.643","common.cef_version":"74.1.19+gb62bacf+chromium-74.0.3729.157","common.client_id":"lol","common.installation_id":"0pSXzA==","common.locale":"en_GB","common.login_session_id":"d2c35be4-9199-aa41-906d-fce9622320cb","common.machine_id":"blgald1BEkW/RsP6dWyFOQ==","common.os_edition":"Ultimate N, x64","common.os_platform":"Windows","common.os_version_major":"7","common.os_version_minor":"Service Pack 1","common.region":"EUW","common.session_id":"e5a44758-eb46-df44-bf50-6b117d285d9a","duration":"404647","occurrenceId":"1","tag":"lol-login-request-rso-token_fail_auth"}
000281.220|   WARN|           rcp-be-lol-login| ProcessRSOLoginSession failed: FAILED_TO_COMMUNICATE_WITH_RSO: RSO Server error: Error response for POST /lol-rso-auth/v1/authorization/gas: server_error: Received invalid JSON
000281.238|   OKAY|           rcp-be-lol-store| HandleLogin calling CheckReady
000281.248|   OKAY| rcp-be-lol-platform-config| PlatformConfigPlugin::HandleLoginSession()
000281.256| ALWAYS|           rcp-be-lol-store| StorePlugin init-status: in-progress ( LoggedIn StoreEndpoint Region Headers )
000281.273|   OKAY|        rcp-be-lol-gameflow| Did not relaunch game because user was not logged in.
000281.290|   WARN|           rcp-be-lol-lobby| Can't check registration status, not connected
000281.297| ALWAYS|      rcp-be-lol-statstones| StatStonesPlugin init-status: in-progress ( StatStonesEnabled )
000281.305| ALWAYS|        rcp-be-lol-rso-auth| RSOAuthPlugin::HandleAuthorizationDelete()
000281.314|   WARN|           rcp-be-lol-login| RSO Login session procesing failed: FAILED_TO_COMMUNICATE_WITH_RSO
000281.723| ALWAYS|                    Tracing| The following message is being collected by the Data API - Channel: riot__rclient__lcu-player-experience-duration  Data: {"common.application_name":"LeagueClient","common.application_version":"10.22.341.643","common.cef_version":"74.1.19+gb62bacf+chromium-74.0.3729.157","common.client_id":"lol","common.installation_id":"0pSXzA==","common.locale":"en_GB","common.login_session_id":"d2c35be4-9199-aa41-906d-fce9622320cb","common.machine_id":"blgald1BEkW/RsP6dWyFOQ==","common.os_edition":"Ultimate N, x64","common.os_platform":"Windows","common.os_version_major":"7","common.os_version_minor":"Service Pack 1","common.region":"EUW","common.session_id":"e5a44758-eb46-df44-bf50-6b117d285d9a","duration":"1090000","occurrenceId":"1","tag":"login-successful-lock-and-load-unlock_failed"}
000281.813| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__feature_error
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 10.22.341.643
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: 0pSXzA==
common.login_session_id: d2c35be4-9199-aa41-906d-fce9622320cb
common.locale: en_GB
common.os_version_major: 7
common.machine_id: blgald1BEkW/RsP6dWyFOQ==
localizationString: Unable to connect to the authentication service. Check the server status <a class='login-external-link' target='_blank' href='http://status.leagueoflegends.com/'>here</a>. If it looks good, follow the guide <a class='login-external-link' target='_blank' href='https://support.riotgames.com/hc/articles/201761944'>here</a>
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: Service Pack 1
plugin: rcp-fe-lol-login
common.region: EUW
common.session_id: e5a44758-eb46-df44-bf50-6b117d285d9a
id: LOGIN_BACKEND_ERROR_MESSAGE
messageId: FAILED_TO_COMMUNICATE_WITH_RSO
message: we recieved an error from /lol-login/v1/session/error
severity: unknown
sessionTime: 259282
000281.859| ALWAYS| Queued Dradis event to be sent.

Hope this help to debug the login error

**Comment by Alekc89** [comment]
You can observe that your PC is using full band-width. It is downloading the latest LOL Version. Please just wait. You will be able to login once the update is finished. But only without the Riot Client. So after the Update is finished, you must delete the Riot Client folder to launch the old game-starter.
