### ISSUE TITLE
Leagueoflegends doesn't start

### ISSUE THREAD

**Issue by MagdyA** [mmtrt/leagueoflegends#222]
I'm facing an issue whenever I start `leagueoflegends` riot client starts but whenever I press `play` it the button keeps shadowed and nothing happens for few minutes and it unshadows again so come and forth

I tried to run
```bash
snap run leagueoflegends
```
to see if there are any issues with the new patch but I get the following output
```bash
0634:err:winediag:WS_getaddrinfo Failed to resolve your host name IP
0938:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```

The game has been going good until the last 2 days

Can you please help?

**Comment by amourelius** [comment]
I believe I have the same issue which seems to correlate with Patch 13.5 this week. 
I played Tuesday, then the client updated and have not been able to since. 

Attempted a complete reinstall with no change. The game installed, client updates and runs, press play and it tries to load showing the "League of Legends" splash after a minute then disappears. The Play button becomes available again. 

I'm not sure where to begin looking for a solution.

**Comment by mmtrt** [comment]
can you update snap and retry again

**Comment by MagdyA** [comment]
Thank you, It is working for me now
